### ISSUE TITLE
사장 가게 등록

### ISSUE THREAD

**Issue by juno-junho** [prgrms-be-devcourse/BE-04-PoMin#10]
사장은 가게를 등록할 수 있다.

## TODO
- [x] #13
     - [x]  이미지 및 이름
 
- [ ] 사장은 form을 통해 name, address, category를 선택하여 입력하면 가게를 등록할 수 있다.
     - [ ] 각 값은 필수적으로 입력해야 하며, 입력하지 않으면 '가게 이름을 입력해 주세요', '가게 이름은 필수 입니다', '카테고리는 하나 이상 반드시 선택하셔야합니다' 의 예외 메세지를 반환한다.
     - [ ] 카테고리는 하나 이상을 반드시 선택해야 한다.
     - [ ] 가게 이름은 공백을 입력 할 수 없다.
