### ISSUE TITLE
로그인 기능 구현

### ISSUE THREAD

**Issue by Juhongseok** [prgrms-be-devcourse/BE-04-PoMin#5]
## User Story
사용자는 서비스를 이용하기 위해 회원 가입 및 로그인을 할 수 있다(소셜)

## TODO
- [x] 사용자 엔티티 고객, 사장으로 분리
- [ ] OAuth login (고객)
- [ ] 일반 로그인 (사장)
- [ ] JWT 발급

---
> Jira: POM-2
